# Generated by Django 4.0.2 on 2022-07-29 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BANKNIFTY', models.CharField(max_length=255, verbose_name='BANKNIFTY')),
                ('DATE', models.IntegerField(verbose_name='DATE')),
                ('TIME', models.IntegerField(verbose_name='TIME')),
                ('OPEN', models.FloatField(verbose_name='OPEN')),
                ('HIGH', models.FloatField(verbose_name='HIGH')),
                ('LOW', models.FloatField(verbose_name='LOW')),
                ('CLOSE', models.FloatField(verbose_name='CLOSE')),
                ('VOLUME', models.FloatField(verbose_name='VOLUME')),
            ],
        ),
    ]
